-- ================= DATABASE =================
CREATE DATABASE IF NOT EXISTS event_booking;
USE event_booking;


-- ================= ADMIN =================
CREATE TABLE ADMIN (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ================= USERS =================
CREATE TABLE USERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- ================= CATEGORY =================
CREATE TABLE CATEGORY (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) UNIQUE NOT NULL,
  DESCRIPTION TEXT
);


-- ================= VENUES =================
CREATE TABLE VENUES (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  LOCATION VARCHAR(150),
  CAPACITY INT
);


-- ================= EVENTS =================
CREATE TABLE EVENTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(150) NOT NULL,
  DESCRIPTION TEXT,
  EVENT_DATE DATE NOT NULL,
  VENUE_ID INT NOT NULL,
  PRICE DECIMAL(10,2),
  TOTAL_SEATS INT NOT NULL,
  AVAILABLE_SEATS INT NOT NULL,
  CATEGORY_ID INT NOT NULL,
  ADMIN_ID INT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (VENUE_ID) REFERENCES VENUES(ID),
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
  FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN(ID)
);


-- ================= BOOKINGS =================
CREATE TABLE BOOKINGS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  EVENT_ID INT NOT NULL,
  QUANTITY INT,
  TOTAL_AMOUNT DECIMAL(10,2),
  STATUS VARCHAR(50) DEFAULT 'CONFIRMED',
  BOOKING_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
  FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(ID) ON DELETE CASCADE
);


-- ================= PAYMENTS =================
CREATE TABLE PAYMENTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BOOKING_ID INT NOT NULL,
  PAYMENT_STATUS VARCHAR(50) DEFAULT 'SUCCESS',
  PAYMENT_METHOD VARCHAR(50),
  PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (BOOKING_ID) REFERENCES BOOKINGS(ID) ON DELETE CASCADE
);